#!/usr/bin/env bash
# check-modules.sh [tree]
#
#   tools/check-modules.sh ~/android
#
# Lists every Soong module that the tree REFERENCES but does not DEFINE.
# On a pruned tree those are the modules that went out with a removed
# project, and each one is a build failure waiting to happen.
#
# Why this is not just "run the build and see":
#
#   - With ALLOW_MISSING_DEPENDENCIES=true (which a pruned tree needs, or
#     Soong panics in validate_bindings.go), a missing dependency becomes a
#     runtime "echo ... && false". You find one, fix it, rebuild, find the
#     next. Six were found that way, one per build, over many hours.
#   - With it unset, Soong panics on the FIRST missing fuzzer rather than
#     reporting anything, so that does not enumerate either.
#
# This reads the Android.bp files directly and reports all of them at once,
# in about two minutes.
#
# It is a heuristic, not a compiler. Expect some false positives: modules
# supplied by prebuilts under a Soong namespace, generated module names,
# and names built by string concatenation will show up as undefined. Treat
# the output as a list to check, not a list of certain failures.

set -eo pipefail

TREE="${1:-$HOME/android}"
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -d "$TREE" ] || { echo "no tree at $TREE" >&2; exit 1; }

python3 - "$TREE" "$SELF" <<'PY'
import os, re, sys, collections

tree = sys.argv[1]
self_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(
    os.path.dirname(os.path.abspath(__file__ if "__file__" in dir() else ".")))

# Names a human has looked at and ruled out. See the file's own header.
allow = set()
_fp = os.path.join(self_dir, "tools", "known-false-positives.txt")
try:
    for line in open(_fp, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if line:
            allow.add(line)
except OSError:
    pass

# A module definition is  name: "something",  inside any module block.
DEF = re.compile(r'^\s*name\s*:\s*"([^"]+)"', re.M)

# Properties whose values are module names rather than paths or flags.
# srcs/exclude_srcs are deliberately absent - those are file paths, and
# ":modname" references inside them are handled separately below.
DEP_PROPS = (
    "defaults static_libs shared_libs libs header_libs whole_static_libs "
    "java_libs required apex_available jni_libs runtime_libs "
    "static_executables export_static_lib_headers export_shared_lib_headers "
    "plugins processor_libs kotlin_plugins data_libs data_bins "
    "tools host_required target_required bootclasspath_fragments "
    "systemserverclasspath_fragments compile_multilib_deps"
).split()

PROP = re.compile(
    r'\b(' + "|".join(DEP_PROPS) + r')\s*:\s*\[([^\]]*)\]', re.S
)
NAME_IN_LIST = re.compile(r'"([^"]+)"')

# A Soong module name, and nothing else. The property regex spans newlines,
# so it can swallow a // comment sitting inside a list; without this, every
# quoted word in that comment is reported as a missing module. Filtering on
# shape is safer than stripping comments, because // also begins a
# visibility label - //visibility:public - and stripping it shreds those.
MODULE_NAME = re.compile(r'^[A-Za-z0-9_][A-Za-z0-9_.+@-]*$')
# ":foo" inside srcs means "the output of module foo"
SRC_MODULE = re.compile(r'"\:([A-Za-z0-9_.+-]+)"')

defined = set()
referenced = collections.defaultdict(set)   # name -> files referencing it

skip = {".repo", ".git", "out"}
scanned = 0
for root, dirs, files in os.walk(tree):
    dirs[:] = [d for d in dirs if d not in skip]
    for fn in files:
        if fn != "Android.bp" and not fn.endswith(".bp"):
            continue
        fp = os.path.join(root, fn)
        scanned += 1
        try:
            text = open(fp, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        rel = os.path.relpath(fp, tree)

        for m in DEF.finditer(text):
            defined.add(m.group(1))

        for m in PROP.finditer(text):
            for n in NAME_IN_LIST.finditer(m.group(2)):
                v = n.group(1)
                v = v.lstrip(":")
                # Paths, visibility labels and anything that is not shaped
                # like a module name.
                if "/" in v or not MODULE_NAME.match(v):
                    continue
                referenced[v].add(rel)

        for m in SRC_MODULE.finditer(text):
            referenced[m.group(1)].add(rel)

# Names that are never .bp module definitions and always look undefined:
#   __subpackages__, //visibility:...   visibility keywords
#   *.stubs, *.stubs.system, ...        generated by Soong from API .txt
#   *-current, *.latest                 API-version aliases
# Soong derives a lot of module names rather than reading them from a
# name: field, so they are referenced everywhere and defined nowhere. All
# of these are generated, not missing:
#
#   __subpackages__, //visibility:...   visibility keywords
#   foo.stubs, foo.stubs.system         java_sdk_library API surfaces
#   foo.impl                            java_sdk_library implementation
#   foo-cpp foo-java foo-ndk foo-rust   aidl_interface backends
#   foo-V3-cpp                          versioned aidl_interface backends
#   libFooProperties                    sysprop_library
#   foo-current, foo.latest             API-version aliases
IGNORE = re.compile(
    r'^__|^//|'
    r'#|'                                   # libdexfile#impl - variant syntax
    r'[<>*]|'                               # pw_rpc_<instance_name>, com.gki.*
    r'\.txt$|'                              # a file, not a module
    r'\.stubs(\.|$)|'
    r'\.impl$|'
    r'-(cpp|java|ndk|rust|ndk_platform)$|'
    r'-V\d+-(cpp|java|ndk|rust)$|'
    r'-(java|cpp|ndk)-source$|'             # generated by aidl_interface
    r'_c_wrapper$|'                         # generated by sysprop/aconfig
    r'-(exportable|module_libs_api|system-stubs)$|'
    r'-(rust|cpp-analyzer|java|cpp|ndk)-source$|'   # aidl_interface backends
    r'-java-(constants|shallow)$|'                  # hidl java gen
    r'^all-(modules|framework|non-updatable)|'      # generated stub aggregates
    r'^allowed_privapp_|'                           # generated privapp lists
    r'_header_file$|'                               # generated headers
    r'\.(h|hpp|txt|xml|json)$|'                     # a file, not a module
    r'-$|'                                          # truncated reference
    r'^sdk_(module-lib|public|system|test)_|'       # SDK snapshot names
    r'\.(vendor_ramdisk|recovery|ramdisk|vendor|product)$|'  # image variants
    r'^libwifi-hal-|'                               # board-selected wifi HALs

    r'^lib[A-Z].*Properties$|'
    r'(^|[.-])(current|latest)$'
)

# Property names themselves, in case a malformed file leaks one through.
IGNORE_EXACT = set(DEP_PROPS)

# Rust crates are referenced by crate name and defined as lib<crate>.
# external/rust/android-crates-io is full of them, and without this every
# crate in the tree looks undefined.
def resolved(n):
    return n in defined or ("lib" + n) in defined

missing = {
    n: f for n, f in referenced.items()
    if not resolved(n) and not IGNORE.search(n)
    and n not in allow and n not in IGNORE_EXACT
}
ignored = sum(
    1 for n in referenced
    if not resolved(n) and (IGNORE.search(n) or n in IGNORE_EXACT)
)

# A reference from a test directory rarely matters for a system image -
# those modules are not in the graph unless you build them. Split them out
# so the list you have to act on is short.
TESTISH = re.compile(r'(^|/)(cts|tests?|.*_tests?|vts|gts|sts|mts)(/|$)')

def testish(files):
    return all(TESTISH.search(os.path.dirname(f)) for f in files)

# Reference count is the signal that survives everything else. Soong
# generates module names from a dozen conventions, and no pattern list
# catches them all - but generated and board-conditional names are almost
# always referenced once, while a project that genuinely went missing is
# referenced by everything that used it: cts_defaults 403 times, lint_api
# 14, glide 8. So a single reference is worth reading, not worth blocking.
THRESHOLD = 2

likely   = {n: f for n, f in missing.items()
            if not testish(f) and len(f) >= THRESHOLD}
singles  = {n: f for n, f in missing.items()
            if not testish(f) and len(f) < THRESHOLD}
testonly = {n: f for n, f in missing.items() if testish(f)}

print("tree      : %s" % tree)
print("scanned   : %d .bp files" % scanned)
print("defined   : %d modules" % len(defined))
print("referenced: %d names" % len(referenced))
print("undefined : %d (%d generated/keyword names filtered out)" % (len(missing), ignored))
print("  blocking - non-test, %d+ references     : %d" % (THRESHOLD, len(likely)))
print("  advisory - non-test, single reference   : %d" % len(singles))
print("  advisory - test directories only        : %d" % len(testonly))
print()

if not missing:
    print("clean: every referenced module is defined somewhere in the tree.")
    sys.exit(0)

if likely:
    print("ACT ON THESE - referenced from code that is not a test, so likely")
    print("in the graph for a normal build:")
    print()
    for name in sorted(likely, key=lambda n: (-len(likely[n]), n)):
        files = sorted(likely[name])
        print("  %-46s %d reference(s)" % (name, len(files)))
        for f in files[:2]:
            print("        %s" % f)
        if len(files) > 2:
            print("        ... and %d more" % (len(files) - 2))
    print()

if singles:
    print("Single reference each - almost always a generated or")
    print("board-conditional name rather than a missing project. Read them,")
    print("do not act on them blindly. Top 10 of %d:" % len(singles))
    for name in sorted(singles)[:10]:
        print("  %-46s %s" % (name, sorted(singles[name])[0]))
    print()

if testonly:
    print("Referenced only from test directories - these bite only if you")
    print("build those tests. Top 10 of %d:" % len(testonly))
    for name in sorted(testonly, key=lambda n: (-len(testonly[n]), n))[:10]:
        print("  %-46s %d reference(s)" % (name, len(testonly[name])))
    print()

print()
print("Each of these is referenced by a build file but defined nowhere in")
print("the tree. On a pruned checkout that usually means the project that")
print("defined it was removed. Find which one upstream defines the module,")
print("comment the entry out in the relevant manifest - keep the line, add")
print("the reason - then:")
print()
print("    repo sync -c -j$(nproc) --no-clone-bundle <project>")
print()
print("Some entries will be false positives: modules provided through a")
print("Soong namespace, or names assembled at build time. Check before")
print("un-pruning.")
sys.exit(1)
PY
